services:
  - type: web
    name: desing-shop
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: |
      python manage.py makemigrations --verbosity 3
      python manage.py migrate --verbosity 3
      python manage.py collectstatic --noinput

    startCommand: gunicorn desing_shop.wsgi:application
