services:
  - type: web
    name: desing-shop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn desing_shop.wsgi:application
    preDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate