# Generated by Django 5.2 on 2025-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalones',
            name='talla',
            field=models.CharField(choices=[('XS', 'Extra Pequeña'), ('S', 'Pequeña'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=2),
        ),
    ]
