# Generated by Django 5.2 on 2025-06-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
