# Generated by Django 5.2 on 2025-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=4)),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
