# Generated by Django 5.2 on 2025-06-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0002_alter_pantalones_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
    ]
