# Generated by Django 5.2 on 2025-06-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0004_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalones',
            name='talla',
        ),
        migrations.AddField(
            model_name='pantalones',
            name='cantidad_l',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantalones',
            name='cantidad_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantalones',
            name='cantidad_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantalones',
            name='cantidad_xl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantalones',
            name='cantidad_xs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
