# Generated by Django 5.2 on 2025-06-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0005_remove_pantalones_talla_pantalones_cantidad_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='cantidad_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='cantidad_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='cantidad_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='cantidad_xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='cantidad_xs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='imagen',
            field=models.ImageField(upload_to='pantalones/'),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='pantalones',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ropaApp.categoria'),
        ),
    ]
