# Generated by Django 4.2 on 2025-06-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0007_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pantalones',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
