# Generated by Django 4.2 on 2025-06-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropaApp', '0008_detallepedido_estado_entrega_alter_pantalones_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ropaApp.usuario'),
        ),
    ]
